// <auto-generated />
namespace MyBookings.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class dropCountries : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dropCountries));
        
        string IMigrationMetadata.Id
        {
            get { return "201910232049370_dropCountries"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
